
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-logging-vlo-io-v1-vectoragent
  failurePolicy: Fail
  name: mvectoragent.kb.io
  rules:
  - apiGroups:
    - logging.vlo.io
    apiVersions:
    - v1
    - v1beta
    operations:
    - CREATE
    - UPDATE
    resources:
    - vectoragents
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-logging-vlo-io-v1-vectoragent
  failurePolicy: Fail
  name: vvectoragents.kb.io
  rules:
  - apiGroups:
    - logging.vlo.io
    apiVersions:
    - v1
    - v1beta
    operations:
    - CREATE
    - UPDATE
    resources:
    - vectoragents
  sideEffects: None
