apiVersion: logging.vlo.io/v1beta
kind: VectorAgent
metadata:
  name: agent
  namespace: logging
  labels:
    logging: vector-agent
spec:
  image: timberio/vector
  tag: 0.21.2-distroless-libc
  metricsScrapeInterval: 15
  internalLogs: true
  logLevel: info
  podAnnotations:
    pod_uid: "kubernetes.pod_id"
    pod_namespace: "kubernetes.namespace_name"
